GET http://localhost:8181/api/v1/product
###
GET http://localhost:8181/api/v1/product/2
###
POST http://localhost:8181/api/v1/product
Content-Type: application/json

{
    "name": "Coca-cola",
    "stock": 120,
    "price": 5000
}
###
DELETE http://localhost:8181/api/v1/product/2
###
PUT http://localhost:8181/api/v1/product
Content-Type: application/json

{
  "id": 1,
  "name": "Teh Pucuk",
  "stock": 100,
  "price": 4500
}